INSERT INTO CATALOG ("PRODUCT_ID","PRODUCT_NAME","STOCK","UNIT_PRICE")
VALUES('CA1','Berlin', 100, 1000);
INSERT INTO CATALOG ("PRODUCT_ID","PRODUCT_NAME","STOCK","UNIT_PRICE")
VALUES('CA2','Seoul', 200, 1500);
INSERT INTO CATALOG ("PRODUCT_ID","PRODUCT_NAME","STOCK","UNIT_PRICE")
VALUES('CA3','Busan', 300, 2000);